In [1]:
import pandas as pd
import numpy as np

# Series
- Series is a column
- Has index-value relationship

In [2]:
di = {
    'one' : 1,
    'two' : 2,
    'three' : 3,
    'four' : 4,
    'five' : 5
}
s1 = pd.Series(di)
s1

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [3]:
print(s1['one'])
print(s1.loc['one'])
print(s1.iloc[0])

1
1
1

In [4]:
li = [1,2,3,4,5]
s1 = pd.Series(np.arange(1, 6))
label = ['one', 'two', 'three', 'four', 'five']

# You can't relabel an existing series like below
# s1 = pd.Series(s1, index=label)

# Instead, you can use .index
s1.index = label
s1

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [5]:
# Slicing
print(s1['two':'four'])
print(s1['three':])
print(s1[::2])
print(s1[::-1])

two      2
three    3
four     4
dtype: int64
three    3
four     4
five     5
dtype: int64
one      1
three    3
five     5
dtype: int64
five     5
four     4
three    3
two      2
one      1
dtype: int64

In [6]:
print(s1.values)
print()
print(s1.value_counts())
print()
print(s1.index)
print()
print(s1.array)

[1 2 3 4 5]

1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

<NumpyExtensionArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: int64

In [7]:
s1['six'] = 6
s1['six-seven'] = 77
s1['six-seven'] = 67
s1

one           1
two           2
three         3
four          4
five          5
six           6
six-seven    67
dtype: int64

In [8]:
s2 = s1.drop('six-seven')
print(s2)

s1.drop('six', inplace=True)
print(s1)

one      1
two      2
three    3
four     4
five     5
six      6
dtype: int64
one           1
two           2
three         3
four          4
five          5
six-seven    67
dtype: int64

In [9]:
s1['anomoly'] = 9867987
s1.drop(['anomoly', 'six-seven'], inplace=True)
s1

one      1
two      2
three    3
four     4
five     5
dtype: int64

# DataFrame

- Tabular Data
- Rows and Columns
- A table

In [10]:
# Ways to make dataframes
# 1. A dictionaary with a keyword and a list of a row
# 2. A list of dictionaries

df1 = pd.DataFrame({
    'name' : ['Kim', 'Lee', 'Choi'],
    'Age' : [23, 34, 13],
    'Gender' : ['Male', 'Female', 'Other']
})
print(df1)

df2 = pd.DataFrame([
    {'name' : 'Kim', 'Age' : 23, 'Gender' : 'Male'},
    {'name' : 'Lee', 'Age' : 34, 'Gender' : 'Female'},
    {'name' : 'Choi', 'Age' : 13, 'Gender' : 'Other'}
])
print(df2)

   name  Age  Gender
0   Kim   23    Male
1   Lee   34  Female
2  Choi   13   Other
   name  Age  Gender
0   Kim   23    Male
1   Lee   34  Female
2  Choi   13   Other

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   Age     3 non-null      int64
 2   Gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes

In [12]:
df1.describe()

             Age
count   3.000000
mean   23.333333
std    10.503968
min    13.000000
25%    18.000000
50%    23.000000
75%    28.500000
max    34.000000

In [13]:
df1.describe(include='all')

       name        Age Gender
count     3   3.000000      3
unique    3        NaN      3
top     Kim        NaN   Male
freq      1        NaN      1
mean    NaN  23.333333    NaN
std     NaN  10.503968    NaN
min     NaN  13.000000    NaN
25%     NaN  18.000000    NaN
50%     NaN  23.000000    NaN
75%     NaN  28.500000    NaN
max     NaN  34.000000    NaN

In [14]:
flight_df = pd.read_csv('../data/flight.csv')
flight_df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [15]:
flight_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [16]:
flight_df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [17]:
flight_df.describe(include='all')

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
count,300153.000000,300153,300153,300153,300153,300153,300153,300153,300153,300153.000000,300153.000000,300153.000000
unique,NaN,6,1561,6,6,3,6,6,2,NaN,NaN,NaN
top,NaN,Vistara,UK-706,Delhi,Morning,one,Night,Mumbai,Economy,NaN,NaN,NaN
freq,NaN,127859,3235,61343,71146,250863,91538,59097,206666,NaN,NaN,NaN
mean,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.221021,26.004751,20889.660523
std,86646.852011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.191997,13.561004,22697.767366
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.830000,1.000000,1105.000000
25%,75038.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.830000,15.000000,4783.000000
50%,150076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.250000,26.000000,7425.000000
75%,225114.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.170000,38.000000,42521.000000
max,300152.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.830000,49.000000,123071.000000

In [20]:
flight_df['class'].value_counts()

class
Economy     206666
Business     93487
Name: count, dtype: int64

In [21]:
flight_df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [22]:
flight_df.sort_values(by='price')

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
206603,206603,Indigo,6E-581,Chennai,Morning,one,Evening,Hyderabad,Economy,9.17,49,1105
206094,206094,Indigo,6E-7185,Chennai,Morning,one,Afternoon,Hyderabad,Economy,4.17,43,1105
206519,206519,Indigo,6E-557,Chennai,Early_Morning,one,Afternoon,Hyderabad,Economy,7.33,48,1105
206520,206520,Indigo,6E-7589,Chennai,Afternoon,one,Night,Hyderabad,Economy,7.50,48,1105
206521,206521,Indigo,6E-7208,Chennai,Early_Morning,one,Afternoon,Hyderabad,Economy,7.67,48,1105
...,...,...,...,...,...,...,...,...,...,...,...,...
270999,270999,Vistara,UK-772,Kolkata,Morning,one,Evening,Hyderabad,Business,9.50,17,114705
277345,277345,Vistara,UK-870,Hyderabad,Night,one,Afternoon,Mumbai,Business,16.42,3,115211
215859,215859,Vistara,UK-809,Delhi,Evening,two_or_more,Evening,Kolkata,Business,21.08,1,116562
216096,216096,Vistara,UK-811,Delhi,Early_Morning,two_or_more,Evening,Kolkata,Business,10.92,5,117307
261377,261377,Vistara,UK-772,Kolkata,Morning,one,Night,Delhi,Business,13.50,3,123071

In [ ]:
super_long_haul = flight_df[flight_df['duration'] >= 20]
super_long_haul.sort_values(by='duration')
# super_long_haul[['source_city', 'destination_city', 'duration']]
super_long_haul[0:5, ['airline', 'price']]

KeyError: ('airline', 'price')