In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../AICE/data/scores.csv')
df

     번호    이름  학년  반     국어     수학     영어     역사      총점     평균  석차
0     1   상연해   3  1  47.16  43.42  38.11  68.52  197.21  49.30  70
1     2   권자욱   3  3  51.22  48.80  58.01  88.19  246.22  61.56  24
2     3   홍희창   3  4  61.66  74.95  70.10  22.03  228.74  57.18  47
3     4  선우제제   3  1  61.08  72.21  70.94  61.26  265.49  66.37   9
4     5  서문환리   3  1  12.45  59.58  61.00  36.99  170.02  42.50  93
..  ...   ...  .. ..    ...    ...    ...    ...     ...    ...  ..
95   96   전용서   3  3  26.14  50.62  80.78  39.80  197.34  49.33  69
96   97   류태은   3  2  57.99  25.74  49.26  44.60  177.59  44.40  89
97   98   류라혜   3  2  46.15  87.08  66.19  30.42  229.84  57.46  45
98   99   명연보   3  3  56.26  57.71  52.49  41.11  207.57  51.89  57
99  100   구성찬   3  2  52.59  84.76  42.34  57.55  237.24  59.31  33

[100 rows x 11 columns]

In [14]:
# groupby()
group_df = df.groupby(by='반')
subjects = ['국어', '영어', '수학', '역사']
display(group_df['역사'].agg(['mean', 'std', 'median']).round(2))
group_df[subjects].agg(['mean', 'std', 'median']).round(2)

    mean    std  median
반
1  47.02  21.12   50.66
2  45.94  12.76   41.02
3  50.91  16.73   48.68
4  47.58  18.99   50.96
5  45.86  21.29   48.96

      국어                   영어                   수학                   역사  \
    mean    std median   mean    std median   mean    std median   mean
반
1  38.59  21.54  41.34  66.89  22.73  70.82  63.27  16.74  62.47  47.02
2  48.52  19.13  48.72  63.68  21.45  59.48  67.97  20.55  69.05  45.94
3  39.07  19.18  41.64  71.05  13.96  69.84  57.80  14.17  56.80  50.91
4  45.43  22.86  44.33  64.47  19.97  59.72  64.00  14.68  64.64  47.58
5  37.68  18.34  35.11  75.11  20.88  70.83  58.43  22.81  59.14  45.86


     std median
반
1  21.12  50.66
2  12.76  41.02
3  16.73  48.68
4  18.99  50.96
5  21.29  48.96

In [18]:
# 상대 구간 나누기, 절대 구간 나누기
df['전체석차'] = df['총점'].rank(ascending='False').astype(int)
df['학업성취도'] = pd.cut(df['전체석차'], bins=[0, 70, 80, 90, 100], right='True', labels=['하', '중하', '중상', '상'])
df['등급'] = pd.qcut(df['총점'], q=4, labels=['4등급', '3등급', '2등급', '1등급'])
df['합격여부'] = np.where(df['평균'] >= 60, '합격', '불합격')

df.head()

,번호,이름,학년,반,국어,수학,영어,역사,총점,평균,석차,전체석차,학업성취도,등급,합격여부
0,1,상연해,3,1,47.16,43.42,38.11,68.52,197.21,49.30,70,31,하,3등급,불합격
1,2,권자욱,3,3,51.22,48.80,58.01,88.19,246.22,61.56,24,77,중하,1등급,합격
2,3,홍희창,3,4,61.66,74.95,70.10,22.03,228.74,57.18,47,54,하,2등급,불합격
3,4,선우제제,3,1,61.08,72.21,70.94,61.26,265.49,66.37,9,92,상,1등급,합격
4,5,서문환리,3,1,12.45,59.58,61.00,36.99,170.02,42.50,93,8,하,4등급,불합격